apiVersion: skaffold/v2beta15
kind: Config
requires:
  - configs: ["infra"]
    path: infra/skaffold.yaml
  - configs: ["rabbitmq-publisher"]
    path: java/rabbitmq-demo/skaffold.yaml
  - configs: ["rabbitmq-consumer-primary"]
    path: python/skaffold.yaml
  - configs: ["rabbitmq-consumer-secondary"]
    path: elixir/skaffold.yaml
build: {}
deploy: {}