apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq-publisher
  name: rabbitmq-publisher
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: rabbitmq-publisher
  type: ClusterIP
