apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: rabbitmq
build: {}
deploy:
  helm:
    releases:
    - name: rabbitmq
      remoteChart: bitnami/rabbitmq
      version: 8.13.1
      valuesFiles:
        - ./charts/values.yaml